#!/usr/bin/env python3
"""Generate the factory parity matrix in docs/factory/README.md from live GitHub state.

Usage:
    python3 scripts/generate_parity_matrix.py --write   # regenerate the table
    python3 scripts/generate_parity_matrix.py --check   # fail if the table is stale

Why this exists
---------------
The parity matrix used to be maintained by hand. It drifted: it claimed
`skill-drift.yml` was present in `common`, which never had it, while five other
repos ran it as a no-op stub. A hand-typed matrix always drifts; a generated one
cannot.

Only mechanically verifiable artifacts belong here — each row is a plain
"does this path exist" probe. Judgment calls (is the e2e gate *good*, is the
installability gate *sufficient*) are not derivable from the API and belong in
GitHub issues, not in a table that will silently rot.

Set GITHUB_TOKEN (or GH_TOKEN) to avoid rate limits. In CI, github.token works.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "docs" / "factory" / "README.md"

BEGIN = "<!-- BEGIN GENERATED PARITY MATRIX -->"
END = "<!-- END GENERATED PARITY MATRIX -->"

ORG = "projectbluefin"

# Core pipeline repos. `iso` is intentionally excluded — it is an extended repo
# and is not on the parity checklist.
REPOS = ["common", "bluefin", "bluefin-lts", "dakota", "actions", "testsuite"]

# (row label, [candidate repo-relative paths]). Existence only — no interpretation.
# A row is "yes" if ANY candidate path exists. Multiple candidates avoid false
# negatives where a tool accepts several config locations.
ARTIFACTS = [
    ("AGENTS.md", ["AGENTS.md"]),
    ("pre-commit", [".pre-commit-config.yaml"]),
    (
        "Lifecycle caller",
        [".github/workflows/bonedigger.yml", ".github/workflows/lifecycle-caller.yml"],
    ),
    (
        "Renovate config",
        [
            "renovate.json",
            ".github/renovate.json",
            ".github/renovate.json5",
            ".renovaterc.json",
        ],
    ),
    ("Skill router (docs/SKILL.md)", ["docs/SKILL.md"]),
    ("Skill catalog (index.json)", ["docs/skills/index.json"]),
]

API = "https://api.github.com"


def _token() -> str | None:
    return os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")


def path_exists(repo: str, path: str) -> bool:
    """True if `path` exists in the default branch of `org/repo`."""
    url = f"{API}/repos/{ORG}/{repo}/contents/{path}"
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    tok = _token()
    if tok:
        req.add_header("Authorization", f"Bearer {tok}")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.status == 200
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return False
        if e.code in (401, 403):
            print(
                f"error: GitHub API returned {e.code} for {repo}/{path}. "
                "Set GITHUB_TOKEN or GH_TOKEN.",
                file=sys.stderr,
            )
            raise SystemExit(2)
        raise
    except urllib.error.URLError as e:
        print(f"error: cannot reach GitHub API ({e.reason})", file=sys.stderr)
        raise SystemExit(2)


def render() -> str:
    header = "| Artifact | " + " | ".join(REPOS) + " |"
    sep = "|---" * (len(REPOS) + 1) + "|"
    lines = [BEGIN, "", header, sep]
    for label, paths in ARTIFACTS:
        cells = [
            "yes" if any(path_exists(r, p) for p in paths) else "—" for r in REPOS
        ]
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    lines += [
        "",
        "Generated by `scripts/generate_parity_matrix.py` from live GitHub state.",
        "Do not edit by hand. Each row is an existence probe; capability quality is",
        "tracked in GitHub issues, not here.",
        "",
        END,
    ]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f"error: {README} is missing the {BEGIN} / {END} markers."
        )
    head = text[: text.index(BEGIN)]
    tail = text[text.index(END) + len(END) :]
    return head + block + tail


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true", help="Regenerate the matrix")
    g.add_argument("--check", action="store_true", help="Fail if the matrix is stale")
    args = ap.parse_args()

    current = README.read_text()
    updated = splice(current, render())

    if args.write:
        if updated == current:
            print("parity matrix already up to date")
            return 0
        README.write_text(updated)
        print(f"wrote {README.relative_to(REPO_ROOT)}")
        return 0

    if updated != current:
        print(
            "error: docs/factory/README.md parity matrix is stale. Run "
            "`python3 scripts/generate_parity_matrix.py --write`.",
            file=sys.stderr,
        )
        return 1
    print("parity matrix is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
